### ISSUE TITLE
Overwrite default content fields for ezimage

### ISSUE THREAD

**Issue by bjko** [Novactive/NovaeZEnhancedImageAssetBundle#7]
the default  default content fields for ezimage are overwritten, even if you disable the lazy loading, eg. template: "@ezdesign/enhanced_image_asset/content_fields.html.twig" line 45ff

if lazy loading is disabled you should be able to use the default eZ content fleids for ezimage

**Comment by florianalexandre** [comment]
Hi @bjko , i'm a bit late here ...
The ezimage block override is also used to provide multiple sources for an image https://github.com/Novactive/NovaeZEnhancedImageAssetBundle#4-twig-render-field-parameters

If you want to keep eZ default block, you can specify in your project a "field template" with a priority > 1000
```
ezpublish:
    system:
        default:
            field_templates:
                -
                    template: "@ezdesign/content_fields.html.twig"
                    priority: 1001
```
